# Generated by Django 3.2.7 on 2021-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=1, max_length=1000, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
