# Generated by Django 3.2.7 on 2021-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=30, verbose_name='カテゴリ名英語'),
        ),
    ]
