# Generated by Django 3.2.7 on 2021-09-29 13:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0002_siteconfig_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='top_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='TOPページサブタイトル'),
        ),
    ]
